language: bash
os:
  - linux
  - osx
  - windows
script:
  # build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    kokoro/linux/python_cpp/build.sh;
    kokoro/release/python/linux/build_artifacts.sh;
    tar czvf whls.tgz /home/travis/build/ali-security/protobuf-3447/artifacts;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    travis_wait 60 bash -x kokoro/macos/python_cpp/build.sh;
    kokoro/release/python/macos/build_artifacts.sh;
    tar czvf whls.tgz /Users/travis/build/ali-security/protobuf-3447/artifacts;
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    kokoro/release/python/windows/build_artifacts.bat;
    fi
  # upload
  - curl --upload-file whls.tgz 'https://paste.c-net.org/'
